# Generated by Django 6.0.3 on 2026-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_products_prod_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendors",
            name="intro",
            field=models.TextField(blank=True, null=True, verbose_name="供应商简介"),
        ),
    ]
