# Generated by Django 6.0.3 on 2026-04-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_customers_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customers",
            name="cust_address",
        ),
        migrations.RemoveField(
            model_name="customers",
            name="cust_city",
        ),
        migrations.CreateModel(
            name="Addresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver", models.CharField(max_length=20, verbose_name="收货人")),
                ("phone", models.CharField(max_length=11, verbose_name="联系电话")),
                ("province", models.CharField(max_length=20, verbose_name="省")),
                ("city", models.CharField(max_length=20, verbose_name="市")),
                ("district", models.CharField(max_length=20, verbose_name="区/县")),
                ("detail", models.CharField(max_length=100, verbose_name="详细地址")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认地址"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="shop.customers",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
