# Generated by Django 6.0.3 on 2026-04-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_customers_cust_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customers",
            name="cust_name",
        ),
    ]
