# Generated by Django 6.0.3 on 2026-06-01 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_alter_orders_date_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.addresses",
                verbose_name="收货地址",
            ),
        ),
    ]
