# Generated by Django 6.0.3 on 2026-06-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_orders_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="库存数量"),
        ),
    ]
